/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface WooProductGift {}
}

declare global {


  interface HTMLWooProductGiftElement extends Components.WooProductGift, HTMLStencilElement {}
  var HTMLWooProductGiftElement: {
    prototype: HTMLWooProductGiftElement;
    new (): HTMLWooProductGiftElement;
  };
  interface HTMLElementTagNameMap {
    'woo-product-gift': HTMLWooProductGiftElement;
  }
}

declare namespace LocalJSX {
  interface WooProductGift {}

  interface IntrinsicElements {
    'woo-product-gift': WooProductGift;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'woo-product-gift': LocalJSX.WooProductGift & JSXBase.HTMLAttributes<HTMLWooProductGiftElement>;
    }
  }
}


